// AUTO-GENERATED by scripts/build-office-atlas.ts. Do not edit by hand.
// To regenerate: `cd frontend && bun run build:office-atlas`
// Source packs:
//   - Antea Free Furniture Office Set (CC-BY 4.0)
//   - 2dPig Pixel Office Asset Pack (CC0)
//   - Ark Pixel Font (12px proportional) (OFL-1.1)

import atlasUrl from "./atlas.png";

export type ModernFurnitureCategory =
  | "bin"
  | "board"
  | "books"
  | "bookshelf"
  | "cabinet"
  | "chair"
  | "coffee"
  | "desk"
  | "folders"
  | "mirror"
  | "papers"
  | "plant"
  | "printer"
  | "sofa"
  | "table"
  | "vending"
  | "wallArt"
  | "wallClock"
  | "wallShelf"
  | "water";

export type ModernFrameRect = { x: number; y: number; w: number; h: number };

export type ModernSpriteMeta = {
  category: ModernFurnitureCategory;
  w: number;
  h: number;
  /** Approximate horizontal footprint radius (atlas px) used by pathfinding. */
  footprintRadius: number;
};

export type ModernAttribution = {
  name: string;
  license: string;
  url: string;
  required: boolean;
};

export const modernAtlasUrl: string = atlasUrl;

export const modernAtlasSize = { w: 256, h: 122 };

/** Names grouped by semantic category, suitable for random pick or rotation. */
export const modernCategories: Record<ModernFurnitureCategory, readonly string[]> = {
  bin: ["Bin"],
  board: ["Board"],
  books: ["Books"],
  bookshelf: ["Bookshelf", "Tall-Bookshelf"],
  cabinet: ["Big-Filing-Cabinet", "Filing-Cabinet-Open", "Filing-Cabinet-Small", "Filing-Cabinet-Tall", "Wide-Filing-Cabinet"],
  chair: ["Boss-Chair", "Chair", "Chair-2"],
  coffee: ["Coffee-Machine"],
  desk: ["Boss-Desk", "Desk", "Desk-2"],
  folders: ["Folders", "Folders-2"],
  mirror: ["Mirror"],
  papers: ["Papers"],
  plant: ["Big-Plant", "Small-Plant"],
  printer: ["Big-Office-Printer", "Printer", "Printer-Furniture"],
  sofa: ["Big-Sofa", "Big-Sofa-2", "Small-Sofa"],
  table: ["Big-Round-Table", "Small-Table"],
  vending: ["Vending-Machine"],
  wallArt: ["Wall-Graph", "Wall-Note", "Wall-Note-2"],
  wallClock: ["Wall-Clock"],
  wallShelf: ["Wall-Shelf"],
  water: ["Water-Dispenser"],
};

/** Per-sprite frame within the atlas (Canvas drawImage source rect). */
export const modernFrames: Record<string, ModernFrameRect> = {
  "Big-Filing-Cabinet": { x: 138, y: 2, w: 32, h: 32 },
  "Big-Office-Printer": { x: 138, y: 36, w: 32, h: 32 },
  "Big-Plant": { x: 36, y: 36, w: 32, h: 32 },
  "Big-Round-Table": { x: 36, y: 70, w: 32, h: 32 },
  "Big-Sofa": { x: 2, y: 2, w: 32, h: 32 },
  "Big-Sofa-2": { x: 172, y: 36, w: 32, h: 32 },
  "Bin": { x: 92, y: 104, w: 16, h: 16 },
  "Board": { x: 74, y: 104, w: 16, h: 16 },
  "Books": { x: 228, y: 70, w: 16, h: 16 },
  "Bookshelf": { x: 218, y: 104, w: 16, h: 16 },
  "Boss-Chair": { x: 70, y: 36, w: 32, h: 32 },
  "Boss-Desk": { x: 70, y: 2, w: 32, h: 32 },
  "Chair": { x: 56, y: 104, w: 16, h: 16 },
  "Chair-2": { x: 110, y: 104, w: 16, h: 16 },
  "Coffee-Machine": { x: 2, y: 104, w: 16, h: 16 },
  "Desk": { x: 36, y: 2, w: 32, h: 32 },
  "Desk-2": { x: 104, y: 2, w: 32, h: 32 },
  "Filing-Cabinet-Open": { x: 2, y: 70, w: 32, h: 32 },
  "Filing-Cabinet-Small": { x: 192, y: 70, w: 16, h: 16 },
  "Filing-Cabinet-Tall": { x: 2, y: 36, w: 32, h: 32 },
  "Folders": { x: 156, y: 70, w: 16, h: 16 },
  "Folders-2": { x: 210, y: 70, w: 16, h: 16 },
  "Mirror": { x: 38, y: 104, w: 16, h: 16 },
  "Papers": { x: 20, y: 104, w: 16, h: 16 },
  "Printer": { x: 164, y: 104, w: 16, h: 16 },
  "Printer-Furniture": { x: 206, y: 36, w: 32, h: 32 },
  "Small-Plant": { x: 200, y: 104, w: 16, h: 16 },
  "Small-Sofa": { x: 70, y: 70, w: 32, h: 32 },
  "Small-Table": { x: 138, y: 70, w: 16, h: 16 },
  "Tall-Bookshelf": { x: 172, y: 2, w: 32, h: 32 },
  "Vending-Machine": { x: 104, y: 70, w: 32, h: 32 },
  "Wall-Clock": { x: 182, y: 104, w: 16, h: 16 },
  "Wall-Graph": { x: 146, y: 104, w: 16, h: 16 },
  "Wall-Note": { x: 236, y: 104, w: 16, h: 16 },
  "Wall-Note-2": { x: 174, y: 70, w: 16, h: 16 },
  "Wall-Shelf": { x: 128, y: 104, w: 16, h: 16 },
  "Water-Dispenser": { x: 206, y: 2, w: 32, h: 32 },
  "Wide-Filing-Cabinet": { x: 104, y: 36, w: 32, h: 32 },
};

/** Per-sprite metadata (category + sizing hints). */
export const modernSpriteMeta: Record<string, ModernSpriteMeta> = {
  "Big-Filing-Cabinet": { category: "cabinet", w: 32, h: 32, footprintRadius: 14 },
  "Big-Office-Printer": { category: "printer", w: 32, h: 32, footprintRadius: 14 },
  "Big-Plant": { category: "plant", w: 32, h: 32, footprintRadius: 13 },
  "Big-Round-Table": { category: "table", w: 32, h: 32, footprintRadius: 13 },
  "Big-Sofa": { category: "sofa", w: 32, h: 32, footprintRadius: 14 },
  "Big-Sofa-2": { category: "sofa", w: 32, h: 32, footprintRadius: 14 },
  "Bin": { category: "bin", w: 16, h: 16, footprintRadius: 6 },
  "Board": { category: "board", w: 16, h: 16, footprintRadius: 6 },
  "Books": { category: "books", w: 16, h: 16, footprintRadius: 6 },
  "Bookshelf": { category: "bookshelf", w: 16, h: 16, footprintRadius: 7 },
  "Boss-Chair": { category: "chair", w: 32, h: 32, footprintRadius: 13 },
  "Boss-Desk": { category: "desk", w: 32, h: 32, footprintRadius: 14 },
  "Chair": { category: "chair", w: 16, h: 16, footprintRadius: 6 },
  "Chair-2": { category: "chair", w: 16, h: 16, footprintRadius: 6 },
  "Coffee-Machine": { category: "coffee", w: 16, h: 16, footprintRadius: 7 },
  "Desk": { category: "desk", w: 32, h: 32, footprintRadius: 14 },
  "Desk-2": { category: "desk", w: 32, h: 32, footprintRadius: 14 },
  "Filing-Cabinet-Open": { category: "cabinet", w: 32, h: 32, footprintRadius: 14 },
  "Filing-Cabinet-Small": { category: "cabinet", w: 16, h: 16, footprintRadius: 7 },
  "Filing-Cabinet-Tall": { category: "cabinet", w: 32, h: 32, footprintRadius: 14 },
  "Folders": { category: "folders", w: 16, h: 16, footprintRadius: 6 },
  "Folders-2": { category: "folders", w: 16, h: 16, footprintRadius: 6 },
  "Mirror": { category: "mirror", w: 16, h: 16, footprintRadius: 6 },
  "Papers": { category: "papers", w: 16, h: 16, footprintRadius: 6 },
  "Printer": { category: "printer", w: 16, h: 16, footprintRadius: 7 },
  "Printer-Furniture": { category: "printer", w: 32, h: 32, footprintRadius: 14 },
  "Small-Plant": { category: "plant", w: 16, h: 16, footprintRadius: 6 },
  "Small-Sofa": { category: "sofa", w: 32, h: 32, footprintRadius: 14 },
  "Small-Table": { category: "table", w: 16, h: 16, footprintRadius: 6 },
  "Tall-Bookshelf": { category: "bookshelf", w: 32, h: 32, footprintRadius: 14 },
  "Vending-Machine": { category: "vending", w: 32, h: 32, footprintRadius: 14 },
  "Wall-Clock": { category: "wallClock", w: 16, h: 16, footprintRadius: 6 },
  "Wall-Graph": { category: "wallArt", w: 16, h: 16, footprintRadius: 6 },
  "Wall-Note": { category: "wallArt", w: 16, h: 16, footprintRadius: 6 },
  "Wall-Note-2": { category: "wallArt", w: 16, h: 16, footprintRadius: 6 },
  "Wall-Shelf": { category: "wallShelf", w: 16, h: 16, footprintRadius: 6 },
  "Water-Dispenser": { category: "water", w: 32, h: 32, footprintRadius: 14 },
  "Wide-Filing-Cabinet": { category: "cabinet", w: 32, h: 32, footprintRadius: 14 },
};

export const modernAttribution: readonly ModernAttribution[] = [
  { name: "Antea Free Furniture Office Set", license: "CC-BY 4.0", url: "https://stcrbcn.itch.io/furniture-office-set", required: true },
  { name: "2dPig Pixel Office Asset Pack", license: "CC0", url: "https://2dpig.itch.io/pixel-office", required: false },
  { name: "Ark Pixel Font (12px proportional)", license: "OFL-1.1", url: "https://github.com/TakWolf/ark-pixel-font", required: false },
];

export const modernAtlasJsonUrl = new URL("./atlas.json", import.meta.url).href;
