/** 从 MainContent 迁出的 Chat/Config 共用样式（后续可按页面拆分）。 */
import type { CSSProperties } from "react";

const styles: Record<string, CSSProperties> = {
  main: { flex: 1, minWidth: 0, minHeight: 0, overflow: "auto", padding: 24 },
  /** 对话页：占满主区、禁止整页横向滚动，三栏各自纵向滚动 */
  mainChat: {
    flex: 1,
    width: "100%",
    maxWidth: "100%",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    padding: 16,
  },
  /** 研究团队三栏工作台：与 IDE 一致占满主内容区，避免外层滚动条截断拖拽 */
  mainTeam: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    padding: 0,
  },
  mainIde: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    padding: 0,
  },
  /** 实时交易 Agent：四段布局（配置 / 对话流 / K线+快捷） */
  mainTrader: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    padding: 0,
  },
  ideWorkbenchOuter: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minHeight: 0,
    width: "100%",
    overflow: "hidden",
  },
  ideMainRow: {
    display: "flex",
    flexDirection: "row",
    flex: 1,
    minHeight: 0,
    width: "100%",
    overflow: "hidden",
  },
  ideLeftPane: {
    display: "flex",
    flexDirection: "column",
    flexGrow: 0,
    flexShrink: 0,
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
  },
  ideGutter: {
    width: 6,
    flexShrink: 0,
    cursor: "col-resize",
    background: "var(--qb-ide-chrome-border, #27272a)",
    alignSelf: "stretch",
  },
  ideRightPane: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
    display: "flex",
    flexDirection: "row",
    alignItems: "stretch",
  },
  ideCenterStack: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  ideChartArea: {
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  ideQuickGutter: {
    width: 1,
    flexShrink: 0,
    background: "var(--qb-ide-chrome-border, #27272a)",
    alignSelf: "stretch",
  },
  title: { fontSize: 26, fontWeight: 700, margin: "0 0 8px", color: "var(--qb-body-fg)" },
  subTitle: { fontSize: 16, margin: "16px 0 8px", color: "var(--qb-body-fg)" },
  form: { display: "flex", gap: 8, marginBottom: 10 },
  input: {
    flex: 1,
    background: "var(--qb-main-input-bg, #18181b)",
    border: "1px solid var(--qb-main-input-border, #27272a)",
    color: "var(--qb-main-input-fg, #e4e4e7)",
    borderRadius: 8,
    padding: "8px 10px",
  },
  textarea: {
    width: "100%",
    minHeight: 140,
    resize: "vertical",
    background: "var(--qb-main-input-bg, #18181b)",
    border: "1px solid var(--qb-main-input-border, #27272a)",
    color: "var(--qb-main-input-fg, #e4e4e7)",
    borderRadius: 8,
    padding: "8px 10px",
    marginBottom: 8,
  },
  select: {
    background: "var(--qb-main-input-bg, #18181b)",
    border: "1px solid var(--qb-main-input-border, #27272a)",
    color: "var(--qb-main-input-fg, #e4e4e7)",
    borderRadius: 8,
    padding: "8px 10px",
  },
  actions: { display: "flex", gap: 8, marginBottom: 8, flexWrap: "wrap", alignItems: "center" },
  meta: { display: "flex", gap: 12, fontSize: 12, color: "var(--qb-main-meta, #a1a1aa)" },
  configPageBody: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 0,
    width: "100%",
  },
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(220px,1fr))", gap: 10 },
  card: {
    background: "var(--qb-main-card-bg, #18181b)",
    border: "1px solid var(--qb-main-card-border, #27272a)",
    borderRadius: 8,
    padding: 12,
  },
  cardButton: {
    background: "var(--qb-main-card-bg, #18181b)",
    border: "1px solid var(--qb-main-card-border, #27272a)",
    borderRadius: 8,
    padding: 12,
    textAlign: "left",
    color: "var(--qb-main-input-fg, #e4e4e7)",
    cursor: "pointer",
  },
  cardName: { fontSize: 13, fontWeight: 600, color: "var(--qb-card-name, #a78bfa)" },
  cardDesc: { fontSize: 12, color: "var(--qb-card-desc, #a1a1aa)", overflowWrap: "anywhere", wordBreak: "break-word" },
  mcpCardBtn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: 4,
    textAlign: "left",
    cursor: "pointer",
    font: "inherit",
    color: "inherit",
  },
  mcpCardBtnSelected: {
    borderColor: "var(--qb-blue)",
    boxShadow: "0 0 0 1px var(--qb-focus-ring)",
  },
  mcpCardPillRow: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    marginTop: 6,
  },
  mcpCardPill: {
    fontSize: 11,
    fontWeight: 600,
    borderRadius: 6,
    padding: "4px 8px",
    lineHeight: 1.35,
    wordBreak: "break-word",
  },
  mcpCardTopRow: { display: "flex", alignItems: "flex-start", gap: 10 },
  mcpStatusDot: { width: 10, height: 10, borderRadius: "50%", flexShrink: 0, marginTop: 4 },
  mcpDetails: {
    marginBottom: 12,
    border:
      "1px solid var(--qb-mcp-details-border, var(--qb-sidebar-border, #27272a))",
    borderRadius: 8,
    padding: "0 12px",
    background:
      "var(--qb-mcp-details-bg, var(--qb-sidebar-nav-bg, #111114))",
    color: "var(--qb-body-fg, #e4e4e7)",
  },
  mcpDetailsSummary: {
    cursor: "pointer",
    padding: "10px 0",
    fontSize: 13,
    color: "var(--qb-main-meta, #a1a1aa)",
    userSelect: "none",
    listStyle: "none",
  } as CSSProperties,
  mcpDetailsSummarySmall: {
    cursor: "pointer",
    padding: "6px 0",
    fontSize: 12,
    color: "var(--qb-main-meta, #71717a)",
    userSelect: "none",
  } as CSSProperties,
  mcpDetailsNested: {
    border:
      "1px solid var(--qb-mcp-details-border, var(--qb-sidebar-border, #27272a))",
    borderRadius: 6,
    padding: "0 10px",
    background:
      "var(--qb-mcp-details-nested-bg, var(--qb-main-card-bg, #0c0c0e))",
    color: "var(--qb-body-fg, #e4e4e7)",
  },
  mcpMarketGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill,minmax(280px,1fr))",
    gap: 12,
  },
  mcpMarketCard: {
    background:
      "var(--qb-mcp-market-card-bg, var(--qb-main-card-bg, #18181b))",
    border:
      "1px solid var(--qb-mcp-market-card-border, var(--qb-main-card-border, var(--qb-sidebar-border, #27272a)))",
    color: "var(--qb-body-fg, #e4e4e7)",
    borderRadius: 10,
    padding: 12,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    cursor: "pointer",
    textAlign: "left",
    transition: "border-color 0.15s ease",
  },
  mcpMarketCardHeader: { display: "flex", alignItems: "flex-start", gap: 8 },
  mcpMarketMeta: {
    fontSize: 11,
    color: "var(--qb-mcp-market-meta, var(--qb-main-meta, #a1a1aa))",
    marginTop: 4,
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    alignItems: "center",
  },
  mcpMarketRisk: {
    fontSize: 10,
    fontWeight: 600,
    padding: "2px 6px",
    borderRadius: 4,
    color: "#fafafa",
  },
  mcpMarketDesc: {
    fontSize: 12,
    color: "var(--qb-mcp-market-desc, var(--qb-body-fg, #d4d4d8))",
    margin: 0,
    lineHeight: 1.45,
    display: "-webkit-box",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  } as CSSProperties,
  mcpMarketChips: { display: "flex", flexWrap: "wrap", gap: 6 },
  mcpMarketChip: {
    fontSize: 10,
    fontWeight: 600,
    padding: "3px 8px",
    borderRadius: 999,
    background:
      "var(--qb-mcp-market-chip-bg, var(--qb-pill-muted-bg, #27272a))",
    color: "var(--qb-mcp-market-chip-fg, var(--qb-body-fg, #e4e4e7))",
    border:
      "1px solid var(--qb-mcp-market-chip-border, var(--qb-sidebar-border, #3f3f46))",
  },
  mcpMarketCmd: {
    fontSize: 11,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, monospace",
    color: "var(--qb-mcp-market-cmd-fg, var(--qb-main-meta, #a1a1aa))",
    background:
      "var(--qb-mcp-market-cmd-bg, var(--qb-sidebar-explorer-bg, #09090b))",
    borderRadius: 6,
    padding: "6px 8px",
    border:
      "1px solid var(--qb-mcp-market-cmd-border, var(--qb-sidebar-border, #27272a))",
    wordBreak: "break-all",
  },
  mcpMarketCardActions: { marginTop: "auto", paddingTop: 4 },
  mcpModalBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 200,
    background: "rgba(0,0,0,0.55)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  mcpModal: {
    width: "min(760px, 100%)",
    maxHeight: "88vh",
    display: "flex",
    flexDirection: "column",
    background: "var(--qb-modal-bg, var(--qb-main-card-bg, #111114))",
    border:
      "1px solid var(--qb-modal-border, var(--qb-main-card-border, var(--qb-sidebar-border, #3f3f46)))",
    color: "var(--qb-body-fg, #e4e4e7)",
    borderRadius: 12,
    boxShadow: "0 24px 48px rgba(0,0,0,0.45)",
  },
  mcpModalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    flexWrap: "wrap",
    padding: "12px 14px",
    borderBottom:
      "1px solid var(--qb-modal-sep, var(--qb-sidebar-border, #27272a))",
  },
  mcpModalBody: { padding: 12, overflow: "auto", flex: 1, minHeight: 0, display: "flex", flexDirection: "column" },
  mcpModalFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
    padding: "10px 14px",
    borderTop:
      "1px solid var(--qb-modal-sep, var(--qb-sidebar-border, #27272a))",
  },
  mcpProbePanel: {
    marginBottom: 10,
    padding: "10px 12px",
    borderRadius: 8,
    border:
      "1px solid var(--qb-mcp-json-border, var(--qb-sidebar-border, #27272a))",
    background: "var(--qb-stream-box-bg, var(--qb-sidebar-explorer-bg, #09090b))",
    color: "var(--qb-stream-box-fg, var(--qb-body-fg, #d4d4d8))",
    flexShrink: 0,
  },
  mcpProbePanelHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    marginBottom: 8,
    fontSize: 12,
  },
  mcpProbeFullMsg: {
    margin: 0,
    maxHeight: 220,
    overflow: "auto",
    fontSize: 11,
    lineHeight: 1.5,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    color: "var(--qb-stream-box-fg, var(--qb-body-fg, #d4d4d8))",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  mcpJsonTextarea: {
    width: "100%",
    minHeight: 320,
    flex: 1,
    resize: "vertical",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: 12,
    lineHeight: 1.45,
    background:
      "var(--qb-mcp-json-bg, var(--qb-main-input-bg, var(--qb-sidebar-explorer-bg, #09090b)))",
    border:
      "1px solid var(--qb-mcp-json-border, var(--qb-main-input-border, var(--qb-sidebar-border, #27272a)))",
    color: "var(--qb-mcp-json-fg, var(--qb-body-fg, #e4e4e7))",
    borderRadius: 8,
    padding: 10,
  },
  streamBox: {
    background:
      "var(--qb-stream-box-bg, var(--qb-sidebar-explorer-bg, #09090b))",
    border:
      "1px solid var(--qb-stream-box-border, var(--qb-sidebar-border, #27272a))",
    borderRadius: 8,
    padding: 10,
    maxHeight: 260,
    overflow: "auto",
    color: "var(--qb-stream-box-fg, var(--qb-body-fg, #d4d4d8))",
    fontSize: 12,
    whiteSpace: "pre-wrap",
  },
  errorBox: {
    background:
      "var(--qb-config-error-bg, var(--qb-pill-error-bg, rgba(239,68,68,0.18)))",
    border:
      "1px solid var(--qb-config-error-border, var(--qb-pill-error-fg, rgba(239,68,68,0.5)))",
    color: "var(--qb-config-error-fg, var(--qb-pill-error-fg, #fecaca))",
    borderRadius: 8,
    padding: "8px 10px",
    marginBottom: 10,
  },
  configHint: {
    fontSize: 12,
    color: "var(--qb-main-meta, #a1a1aa)",
    margin: "0 0 10px",
    lineHeight: 1.5,
  },
  chatPageRoot: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    background: "var(--qb-chat-page-bg)",
    width: "100%",
    maxWidth: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  chatChrome: {
    flexShrink: 0,
    minWidth: 0,
  },
  chatLayout: {
    display: "grid",
    /** 列宽由 ChatPanel 内联 gridTemplateColumns 控制（会话列表 px + 拖拽条 + 主对话区） */
    gridTemplateRows: "minmax(0, 1fr)",
    gap: 10,
    flex: 1,
    width: "100%",
    maxWidth: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    alignContent: "stretch",
  },
  chatLayoutIde: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    width: "100%",
    maxWidth: "100%",
    gridTemplateRows: "minmax(0, 1fr)",
    gap: 8,
  },
  chatColResizer: {
    margin: 0,
    padding: 0,
    border: "none",
    width: 6,
    minWidth: 6,
    maxWidth: 6,
    borderRadius: 4,
    cursor: "col-resize",
    touchAction: "none",
    background: "var(--qb-chat-resizer-bg, #27272a)",
    alignSelf: "stretch",
    flexShrink: 0,
    opacity: 0.55,
  } satisfies CSSProperties,
  chatIdeRoot: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    overflow: "hidden",
  },
  chatIdeHeader: {
    flexShrink: 0,
    fontSize: 12,
    color: "var(--qb-chat-ide-header-fg, #a1a1aa)",
    padding: "8px 12px",
    borderBottom: "1px solid var(--qb-chat-border, #27272a)",
    background: "var(--qb-chat-ide-header-bg, #111114)",
  },
  chatSidebar: {
    border: "1px solid var(--qb-chat-border, #27272a)",
    borderRadius: 8,
    padding: 10,
    background: "var(--qb-chat-sidebar-bg, #111114)",
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  chatSessionsTop: {
    flexShrink: 0,
    maxHeight: 120,
    width: "100%",
    flex: "0 0 auto",
    padding: "6px 8px",
  },
  chatSessionsToolbar: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexShrink: 0,
    marginBottom: 8,
    flexWrap: "nowrap",
  },
  chatSessionsToolbarTop: {
    marginBottom: 0,
    gap: 8,
    minWidth: 0,
  },
  chatSessionActions: {
    display: "inline-flex",
    alignItems: "center",
    gap: 2,
    flexShrink: 0,
    marginLeft: "auto",
  },
  chatSessionActionDivider: {
    width: 1,
    height: 16,
    margin: "0 4px",
    background: "var(--qb-chat-border, #3f3f46)",
    opacity: 0.85,
  },
  chatSessionLayoutToggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 2,
  },
  chatSessionList: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    overflowY: "auto",
    overflowX: "hidden",
    minHeight: 0,
    flex: 1,
  },
  chatSessionListTop: {
    flexDirection: "row",
    overflowX: "auto",
    overflowY: "hidden",
    flex: "0 0 auto",
    paddingBottom: 2,
  },
  chatSessionListTopInline: {
    flex: "1 1 auto",
    minWidth: 0,
    marginBottom: 0,
  },
  chatSessionItemTop: {
    minWidth: 132,
    maxWidth: 200,
    flex: "0 0 auto",
  },
  chatSessionItem: {
    border: "1px solid var(--qb-chat-border, #27272a)",
    borderRadius: 8,
    background: "var(--qb-chat-session-item-bg, #18181b)",
    color: "var(--qb-chat-session-item-fg, #e4e4e7)",
    textAlign: "left",
    padding: "8px 10px",
    cursor: "pointer",
  },
  chatSessionItemActive: {
    borderColor: "var(--qb-chat-session-active-border, #7c3aed)",
    background: "var(--qb-chat-session-active-bg, transparent)",
  },
  chatMain: {
    border: "1px solid var(--qb-chat-border, #27272a)",
    borderRadius: 8,
    padding: 10,
    background: "var(--qb-chat-main-bg, #111114)",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    flex: 1,
    width: "100%",
  },
  chatMessages: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    overflowY: "auto",
    overflowX: "hidden",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginBottom: 10,
  },
  chatForm: {
    display: "flex",
    gap: 8,
    marginBottom: 0,
    flexShrink: 0,
    minWidth: 0,
  },
  chatBubble: {
    padding: "8px 10px",
    borderRadius: 8,
    border: "1px solid var(--qb-chat-bubble-border, #27272a)",
    minWidth: 0,
    boxSizing: "border-box",
  },
  chatBubbleUser: {
    background: "var(--qb-chat-bubble-user-bg, #27272a)",
    color: "var(--qb-chat-bubble-user-fg, #fafafa)",
    alignSelf: "flex-end",
    maxWidth: "min(82%, 100%)",
  },
  chatBubbleAgent: {
    background: "var(--qb-chat-bubble-agent-bg, #18181b)",
    color: "var(--qb-chat-bubble-agent-fg, #e4e4e7)",
    alignSelf: "flex-start",
    maxWidth: "100%",
  },
  chatMeta: { fontSize: 11, color: "var(--qb-chat-meta-fg, var(--qb-main-meta, #a1a1aa))", marginBottom: 4 },
  chartCtxBanner: {
    fontSize: 12,
    color: "var(--qb-chat-chart-banner-fg, #a5b4fc)",
    background: "var(--qb-chat-chart-banner-bg, #1e1b4b)",
    border: "1px solid var(--qb-chat-chart-banner-border, #4338ca)",
    borderRadius: 8,
    padding: "8px 12px",
    marginBottom: 10,
  },
  errorText: { fontSize: 12, color: "#fca5a5", marginTop: 6 },
};


export { styles };
