import { randomUUID } from "node:crypto";
import { watch, type FSWatcher } from "node:fs";
import { eq } from "drizzle-orm";
import { END, START, StateGraph } from "@langchain/langgraph";
import { getDb } from "../../db/sqlite/client";
import { agentDefinition, agentInstance, agentStep, workflowRun } from "../../db/sqlite/schema";
import type { TaskAssignPayload } from "../../types/a2a";
import type { AgentRole } from "../../types/entities";
import type { RuntimeAgentDefinition } from "../types";
import { stepStreamBus } from "./event-stream";
import { actNode } from "./nodes/act";
import { observeNode } from "./nodes/observe";
import { perceiveNode } from "./nodes/perceive";
import { reasonNode } from "./nodes/reason";
import { sandboxExecutor } from "../sandbox-executor";
import { createInitialGraphState, type AgentGraphState, type StepStreamEvent } from "./state";
import {
  ensureWorkspaceRuntimeConfigFiles,
  loadWorkspaceRuntimeConfig,
  type WorkspaceSandboxPolicy,
} from "../config/workspace-config";
import { syncWorkspaceConfigToDb } from "../config/config-sync";

type GraphAgentView = {
  instanceId: string;
  definitionId: string;
  role: AgentRole;
  version: string;
  status: "idle" | "running" | "error" | "stopped";
};

const DEFAULT_SANDBOX_POLICY_ID = "default-policy";

const DEFAULT_DEFINITIONS: RuntimeAgentDefinition[] = [
  {
    id: "def-orchestrator",
    role: "orchestrator",
    name: "Orchestrator",
    version: "2.0.0",
    systemPrompt: "Task decomposition and workflow coordination.",
    tools: ["task_decompose", "assign_task"],
    mcpServers: [],
    skills: [],
    subscriptions: ["TASK_ASSIGN", "TASK_RESULT", "ALERT", "RISK_BLOCK"],
    llmProvider: "openai:gpt-4o-mini",
    maxIterations: 20,
    sandboxPolicyId: DEFAULT_SANDBOX_POLICY_ID,
    enabled: true,
  },
  {
    id: "def-research",
    role: "research",
    name: "Research",
    version: "2.0.0",
    systemPrompt: "Run factor research and strategy iteration.",
    tools: ["compute_factors", "run_experiment", "version_strategy"],
    mcpServers: [],
    skills: ["momentum-factor"],
    subscriptions: ["TASK_ASSIGN", "MODEL_UPDATE"],
    llmProvider: "openai:gpt-4o-mini",
    maxIterations: 20,
    sandboxPolicyId: DEFAULT_SANDBOX_POLICY_ID,
    enabled: true,
  },
  {
    id: "def-backtest",
    role: "backtest",
    name: "Backtest",
    version: "2.0.0",
    systemPrompt: "Run backtest with historical data only.",
    tools: ["run_backtest", "get_backtest_status"],
    mcpServers: [],
    skills: [],
    subscriptions: ["TASK_ASSIGN"],
    llmProvider: "openai:gpt-4o-mini",
    maxIterations: 20,
    sandboxPolicyId: DEFAULT_SANDBOX_POLICY_ID,
    enabled: true,
  },
];

const DEFAULT_POLICIES: WorkspaceSandboxPolicy[] = [
  {
    id: "default-policy",
    name: "default-policy",
    description: "Default policy generated by runtime bootstrap.",
    allowedTools: [
      "task_decompose",
      "assign_task",
      "compute_factors",
      "run_experiment",
      "version_strategy",
      "run_backtest",
      "get_backtest_status",
    ],
    allowedMcpServers: [],
    allowedConnectors: [],
    allowedHosts: [],
    allowedFsPaths: [],
    maxToolCallMs: 30_000,
    maxIterationsPerRun: 20,
    maxOutputTokens: 4096,
    isolationLevel: "none",
    canWriteMemory: true,
    canReadLiveMarket: false,
    canSubmitOrder: false,
  },
];

export class GraphRunner {
  private definitions = new Map<AgentRole, RuntimeAgentDefinition>();
  private views = new Map<AgentRole, GraphAgentView>();
  private started = false;
  private configWatcher: FSWatcher | null = null;
  private reloadTimer: ReturnType<typeof setTimeout> | null = null;
  private reloading = false;

  async start(): Promise<void> {
    if (this.started) return;
    await this.syncFromWorkspaceConfig();
    const db = await getDb();
    const dbDefs = await db.select().from(agentDefinition);
    const sourceDefs = (dbDefs.length
      ? dbDefs.map(
          (d): RuntimeAgentDefinition => ({
            id: d.id,
            role: d.role,
            name: d.name,
            version: d.version,
            systemPrompt: d.systemPrompt,
            tools: d.toolsJson as string[],
            mcpServers: d.mcpServersJson as string[],
            skills: d.skillsJson as string[],
            subscriptions: d.subscriptionsJson as RuntimeAgentDefinition["subscriptions"],
            llmProvider: d.llmProvider,
            maxIterations: d.maxIterations,
            sandboxPolicyId: d.sandboxPolicyId,
            enabled: d.enabled === 1,
          })
        )
      : DEFAULT_DEFINITIONS
    ).filter((d) => d.enabled);

    for (const def of sourceDefs) {
      this.definitions.set(def.role, def);
      this.views.set(def.role, {
        instanceId: `graph-${def.role}`,
        definitionId: def.id,
        role: def.role,
        version: def.version,
        status: "running",
      });
    }
    this.started = true;
    this.startConfigWatcher();
  }

  async stop(): Promise<void> {
    for (const view of this.views.values()) view.status = "stopped";
    this.stopConfigWatcher();
    this.definitions.clear();
    this.views.clear();
    this.started = false;
  }

  async reload(): Promise<{ before: number; after: number }> {
    const before = this.getViews().length;
    await this.stop();
    await this.start();
    return { before, after: this.getViews().length };
  }

  getViews(): GraphAgentView[] {
    return [...this.views.values()];
  }

  private async syncFromWorkspaceConfig(): Promise<void> {
    const loaded = await loadWorkspaceRuntimeConfig();
    if (!loaded.exists || !loaded.config) {
      await ensureWorkspaceRuntimeConfigFiles({
        definitions: DEFAULT_DEFINITIONS,
        policies: DEFAULT_POLICIES,
      });
      const reloaded = await loadWorkspaceRuntimeConfig();
      if (reloaded.exists && reloaded.config) {
        await syncWorkspaceConfigToDb(reloaded.config);
      }
      return;
    }
    await syncWorkspaceConfigToDb(loaded.config);
  }

  private startConfigWatcher(): void {
    if (this.configWatcher) return;
    this.configWatcher = watch(".qubit", { recursive: false }, (_, fileName) => {
      if (!fileName || !fileName.endsWith(".json")) return;
      if (this.reloadTimer) clearTimeout(this.reloadTimer);
      this.reloadTimer = setTimeout(() => {
        void this.reloadFromWatcher();
      }, 250);
    });
  }

  private stopConfigWatcher(): void {
    if (this.reloadTimer) {
      clearTimeout(this.reloadTimer);
      this.reloadTimer = null;
    }
    if (this.configWatcher) {
      this.configWatcher.close();
      this.configWatcher = null;
    }
  }

  private async reloadFromWatcher(): Promise<void> {
    if (this.reloading) return;
    this.reloading = true;
    try {
      await this.reload();
      console.log("[GraphRunner] workspace config changed, reloaded.");
    } catch (error) {
      console.error("[GraphRunner] workspace config reload failed:", error);
    } finally {
      this.reloading = false;
    }
  }

  async runRoleTask(params: {
    workflowId: string;
    role: AgentRole;
    payload: TaskAssignPayload;
    traceId?: string;
  }): Promise<{ runId: string }> {
    const def = this.definitions.get(params.role);
    if (!def) throw new Error(`No graph definition for role=${params.role}`);

    const runId = randomUUID();
    const traceId = params.traceId ?? randomUUID();
    void this.executeGraph({
      runId,
      traceId,
      def,
      workflowId: params.workflowId,
      payload: params.payload,
    });
    return { runId };
  }

  private async executeGraph(params: {
    runId: string;
    traceId: string;
    def: RuntimeAgentDefinition;
    workflowId: string;
    payload: TaskAssignPayload;
  }): Promise<void> {
    const db = await getDb();
    const agentInstanceId = randomUUID();

    await db.insert(agentInstance).values({
      id: agentInstanceId,
      definitionId: params.def.id,
      workflowRunId: params.workflowId,
      status: "running",
      currentIteration: 0,
      startedAt: new Date().toISOString(),
    });

    const initialState = createInitialGraphState({
      runId: params.runId,
      workflowId: params.workflowId,
      traceId: params.traceId,
      agentDefinition: params.def,
      inboundMessage: {
        messageId: randomUUID(),
        workflowId: params.workflowId,
        traceId: params.traceId,
        senderAgent: "system",
        receiverAgent: agentInstanceId,
        messageType: "TASK_ASSIGN",
        payload: params.payload,
        priority: 50,
        createdAt: new Date().toISOString(),
      },
    });
    let state = initialState;

    const emit = (event: StepStreamEvent) => {
      state.events.push(event);
      stepStreamBus.publish(event);
    };

    const graph = new StateGraph({
      channels: {
        state: {
          value: (x: AgentGraphState, y: Partial<AgentGraphState>) => ({ ...x, ...y }),
          default: () => initialState,
        },
      },
    }) as any;

    graph.addNode("perceive", async (input: { state: AgentGraphState }) => {
      const s = input.state;
      const perceiveStepId = randomUUID();
      await db.insert(agentStep).values({
        id: perceiveStepId,
        agentInstanceId,
        workflowRunId: params.workflowId,
        stepIndex: 0,
        phase: "perceive",
        thought: "Read inbound message and memory context",
        actionType: "memory_read",
        actionJson: { payload: params.payload },
      });
      const partial = await perceiveNode(s);
      return { state: { ...s, ...partial } };
    });

    graph.addNode("reason", async (input: { state: AgentGraphState }) => {
      const nextIteration = input.state.iteration + 1;
      const iterationCheck = await sandboxExecutor.checkIterationLimit({
        runId: params.runId,
        workflowId: params.workflowId,
        traceId: params.traceId,
        agentInstanceId,
        definition: params.def,
        currentIteration: nextIteration,
      });
      if (!iterationCheck.allowed) {
        emit({
          runId: params.runId,
          workflowId: params.workflowId,
          traceId: params.traceId,
          role: params.def.role,
          type: "observe",
          stepIndex: input.state.iteration,
          ts: Date.now(),
          payload: {
            code: "SANDBOX_ITERATION_LIMIT",
            alertType: "iteration_exceeded",
            message: iterationCheck.reason ?? "iteration blocked by sandbox",
          },
        });
        return {
          state: {
            ...input.state,
            finalResponse: {
              status: "terminated",
              reason: "sandbox_iteration_limit",
              iteration: input.state.iteration,
            },
          },
        };
      }
      await db
        .update(agentInstance)
        .set({ currentIteration: nextIteration })
        .where(eq(agentInstance.id, agentInstanceId));
      const reasonStepId = randomUUID();
      await db.insert(agentStep).values({
        id: reasonStepId,
        agentInstanceId,
        workflowRunId: params.workflowId,
        stepIndex: nextIteration,
        phase: "reason",
        thought: "Reasoning with LLM provider",
        actionType: "tool_call",
        actionJson: { llmProvider: params.def.llmProvider },
      });
      const partial = await reasonNode(
        { ...input.state, iteration: nextIteration },
        emit
      );
      return { state: { ...input.state, iteration: nextIteration, ...partial } };
    });

    graph.addNode("act", async (input: { state: AgentGraphState }) => {
      const s = input.state;
      const actStepId = randomUUID();
      await db.insert(agentStep).values({
        id: actStepId,
        agentInstanceId,
        workflowRunId: params.workflowId,
        stepIndex: s.iteration,
        phase: "act",
        thought: "Execute selected tool",
        actionType: "tool_call",
        actionJson: { plannedAction: s.plannedAction },
      });
      const partial = await actNode(s, emit, agentInstanceId, actStepId);
      return { state: { ...s, ...partial } };
    });

    graph.addNode("observe", async (input: { state: AgentGraphState }) => {
      const s = input.state;
      const partial = await observeNode(s, emit, agentInstanceId);
      return { state: { ...s, ...partial } };
    });

    graph.addNode("finalize", async (input: { state: AgentGraphState }) => {
      const s = input.state;
      const forceLoop = Boolean(params.payload.params?.["forceLoop"]);
      const exceeded = forceLoop && s.iteration >= params.def.maxIterations;
      if (exceeded) {
        emit({
          runId: params.runId,
          workflowId: params.workflowId,
          traceId: params.traceId,
          role: params.def.role,
          type: "observe",
          stepIndex: s.iteration,
          ts: Date.now(),
          payload: {
            code: "MAX_ITERATIONS",
            alertType: "iteration_exceeded",
            message: "graph terminated by max iterations",
          },
        });
      }
      const finalResponse = exceeded
        ? { status: "terminated", reason: "max_iterations", iteration: s.iteration }
        : {
            status: "completed",
            role: params.def.role,
            iteration: s.iteration,
            observation: s.observations.at(-1) ?? {},
          };
      return { state: { ...s, finalResponse } };
    });

    graph.addEdge(START, "perceive");
    graph.addEdge("perceive", "reason");
    graph.addEdge("reason", "act");
    graph.addEdge("act", "observe");
    graph.addConditionalEdges(
      "observe",
      (input: { state: AgentGraphState }) => {
        if (input.state.finalResponse) return "finalize";
        const forceLoop = Boolean(params.payload.params?.["forceLoop"]);
        if (forceLoop && input.state.iteration < params.def.maxIterations) {
          return "reason";
        }
        return "finalize";
      },
      { reason: "reason", finalize: "finalize" }
    );
    graph.addEdge("finalize", END);

    const app = graph.compile();
    const result = (await app.invoke({ state: initialState })) as { state: AgentGraphState };
    state = result.state;

    await db
      .update(agentInstance)
      .set({
        status: "stopped",
        endedAt: new Date().toISOString(),
      })
      .where(eq(agentInstance.id, agentInstanceId));
    await db
      .update(workflowRun)
      .set({ status: state.finalResponse?.["status"] === "terminated" ? "failed" : "completed" })
      .where(eq(workflowRun.id, params.workflowId));

    emit({
      runId: params.runId,
      workflowId: params.workflowId,
      traceId: params.traceId,
      role: params.def.role,
      type: "final",
      stepIndex: state.iteration,
      ts: Date.now(),
      payload: state.finalResponse ?? { status: "completed" },
    });
    stepStreamBus.close(params.runId);
  }
}

export const graphRunner = new GraphRunner();

