import type { CatBreed, ScreenMode } from "../types";

export type FrameRect = { x: number; y: number; w: number; h: number };

export type CatPoseName = "idle" | "walk1" | "walk2" | "work" | "success" | "fail" | "empty";

export type AssetBundleId = "comic_bc" | "flat_cool";

export type CatSheetEntry = {
  /** URL of the alpha-trimmed PNG (white background already removed). */
  url: string;
  /** Cat breeds present on this sheet, in row order. */
  breeds: readonly CatBreed[];
  /**
   * Per-cell precise content bbox, keyed by `${breed}_${pose}`.
   * Generated by `frontend/scripts/build-pixel-office-v2.ts`.
   */
  frames: Readonly<Record<string, FrameRect>>;
};

export type AssetBundleManifest = {
  id: AssetBundleId;
  label: string;
  sceneBgUrl: string;
  cats: {
    sheets: ReadonlyArray<CatSheetEntry>;
    poses: readonly CatPoseName[];
  };
  props: {
    /** URL of the alpha-trimmed props PNG. */
    url: string;
    /** Precise content bboxes for every named prop. */
    frames: Readonly<Record<string, FrameRect>>;
    monitorByScreenMode: Record<ScreenMode, string>;
  };
  render: {
    catScaleBase: number;
    deskScaleBase: number;
    monitorScaleBase: number;
    shelfScaleBase: number;
    rackScaleBase: number;
  };
};

export type LoadedAssetBundle = {
  manifest: AssetBundleManifest;
  sceneBg: HTMLImageElement;
  catSheets: HTMLImageElement[];
  props: HTMLImageElement;
  loaded: true;
};
