/** 与 ambient-3d.css 中 3D 模块选择器保持一致，供 hover 倾斜脚本使用 */
export const A3D_TILT_SELECTOR = [
  ".qb-a3d-tilt",
  ".qb-context-card",
  ".qb-agent-shell",
  ".qb-nav-activity-btn",
  ".qb-nav-row",
  ".qb-icon-btn",
  ".qb-btn-primary",
  ".qb-btn-primary-brand",
  ".qb-btn-secondary",
  ".qb-btn-ghost",
  ".qb-chip",
  ".qb-segmented__tab",
  ".qb-pill-tab",
  "[data-qb-team-shell] > div > aside",
  ".qb-team-main-stage",
  "[data-qb-team-research-panel]",
  "[data-qb-team-graph-host]",
  "[data-qb-team-research-panel] [data-qb-team-live-feed]",
  "[data-qb-chat-panel] .qb-chat-bubble",
  "[data-qb-chat-panel] .qb-chat-sidebar",
  "[data-qb-chat-panel] .qb-chat-board-col",
  "[data-qb-chat-panel] .qb-chat-session-list button[type='button']",
  "[data-qb-config-center] details",
  "[data-qb-config-center] .qb-config-stream-box",
  "[data-qb-news-section] article",
  "[data-qb-topology-canvas]",
  "[data-qb-trader-root] > details",
  "[data-qb-trader-root] .qb-trader-module",
  ".qb-monitor__kpi",
  ".qb-monitor__panel",
  ".qb-mcp-chip",
].join(",");
